
node('jenkins-agent-gh-docker') {
    stage('checkout scm') {
        cleanWs()
        checkout scm
    }

    def isAnyParams = params.size() != 0

    stage("properties") {
        load('src/config.groovy')
        properties([
            disableConcurrentBuilds(),
            parameters(gh_actions_params_keys.collect {
                all_params[it]
            }),
        ])
    }

    if(isAnyParams) {
        stage('gh actions') {
            withCredentials([string(credentialsId: 'rvck_gh_token', variable: 'GH_TOKEN')]) {
                sh 'bash gh_actions/run.sh'
            }
        }
    }
}
