inputs:
  FETCH_REF:
    description: '需要拉取的代码分支或commit_sha'
    required: false
    default: ${{ github.ref }}
  REPO:
    description: 'kernel repo'
    required: false
    default: ${{ github.repositoryUrl	}}

outputs:
  kernel_download_url:
    description: "kernel download url"
    value: ${{ steps.build-kernel.outputs.kernel_download_url }}

runs:
  using: "composite"
  steps:        
    - name: build-kernel
      id: build-kernel
      shell: bash
      env:
        FETCH_REF: ${{ inputs.FETCH_REF }}
        REPO: ${{ inputs.REPO }}
        GIT_FETCH_DEPTH: 1
      run: |
        rm -rf kernel || true
        mkdir -p kernel
        cd kernel
        bash ../src/git-fetch-in-dir.sh "$FETCH_REF"
        bash ../rvck-kernel-build/run.sh

        if [ ! -f kernel_download_url ]; then
          echo "kernel_download_url not found"
          exit 1
        fi
        echo "kernel_download_url=$(cat kernel_download_url)" >> $GITHUB_OUTPUT
    

