name: Docker Image CI

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - 'run-in-docker/Dockerfile'

env:
  REGISTRY: hub.oepkgs.net
  IMAGE_NAME: oerv-ci/rava-action-runner

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to ${{ env.REGISTRY }}
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ vars.DOCKERHUB_OEPKGS_OERVCI_USERNAME }}
        password: ${{ secrets.DOCKERHUB_OEPKGS_OERVCI_TOKEN }}
    
    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    #   with:
    #     platforms: linux/riscv64
    #     cleanup: true

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: .github/actions-runner-image/Dockerfile
        no-cache: true
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest