name: kunit-build

on:
  workflow_call:
    inputs:
      WORKFLOW_REPO:
        required: true
        type: string
        description: 工作流脚本仓库

      WORKFLOW_REF:
        required: true
        type: string
        description: 工作流脚本分支
        
      kernel_src_repo:
        type: string
        required: true
        description: '内核源码仓库'
      fetch_ref:
        type: string
        required: true
        description: '内核分支或sha值'
      issue_id:
        type: string
        required: false
      download_server: 
        type: string
        required: false
        default: 10.213.6.54
      download_server_dir: 
        type: string
        required: false
        default: '/usr/share/nginx/html/download/kernel-build-results'
    
    outputs:
      kernel_download_url:
        value: ${{ jobs.kernel-build.outputs.kernel_download_url }}
      summary_content:
        value: ${{ jobs.kernel-build.outputs.summary_content }}
    
    # secrets:
    #   sshkey_content: 
    #     required: true
    #     description: '上传内核所需ssh私钥'

jobs:
  kernel-build:
    runs-on: 'action-runner-9950x-196.2'
    container:
      image: 'hub.oepkgs.net/oerv-ci/rava-action-runner:latest'
      volumes:
        - /srv/nginx/kernel-build:/srv/nginx/kernel-build
    outputs:
      kernel_download_url: ${{ steps.publish-kernel.outputs.kernel_download_url }}
      summary_content: ${{ steps.summary.outputs.summary_content }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_ID: ${{ inputs.issue_id }}
      REPO: ${{ inputs.kernel_src_repo }}
      kernel_result_dir: kernel-result

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.WORKFLOW_REPO }}
          ref: ${{ inputs.WORKFLOW_REF }}
      
      - name: checkout kernel-src
        env:
          GIT_FETCH_DEPTH: 1
        run: |
            rm -rf kernel-src || true
            mkdir kernel-src
            (cd kernel-src && bash ../src/git-fetch-in-dir.sh "${{ inputs.fetch_ref }}")
      
      # - name: before
      #   env:
      #     ADD_LABEL: kernel_building
      #     COMMENT_CONTENT: start kernel build
      #   run: bash gh_actions/run.sh || true

      - name: run kernel build
        id: kernel-build
        run: |
          (
          cd "kernel-src"
          export ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu-
          make distclean
          make openeuler_defconfig
          make Image -j$(nproc)
          make modules -j$(nproc)
          make dtbs -j$(nproc)

          make INSTALL_MOD_PATH="$kernel_result_dir" modules_install -j$(nproc)
          mkdir -p "$kernel_result_dir/dtb/thead"
          cp vmlinux "$kernel_result_dir"
          cp arch/riscv/boot/Image "$kernel_result_dir/Image"
          (cd "$kernel_result_dir" && tar -czf kernel.tar.gz Image)
          
          install -m 644 $(find arch/riscv/boot/dts/ -name "*.dtb") "$kernel_result_dir"/dtb
          mv $(find arch/riscv/boot/dts/ -name "th1520*.dtb") "$kernel_result_dir"/dtb/thead
          )

          echo "suffix=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      
      - name: publish kernel
        id: publish-kernel
        env:
          runner_name: ${{ runner.name }}
        run: |
          kernel_dir_uniq_name="$(echo "${REPO%.git}" | awk -F'/' '{print $(NF-1)"_"$NF}')_${ISSUE_ID}"
          target_dir="/srv/nginx/kernel-build/$kernel_dir_uniq_name"
          if [ -d "$target_dir" ]; then
             rm -rf "$target_dir"
          fi
          cp -r "kernel-src/$kernel_result_dir" "$target_dir"
          echo "kernel_download_url='http://10.30.${runner_name##*-}:8080/${kernel_dir_uniq_name}/Image'" >> $GITHUB_OUTPUT
      
      - name: summary
        if: ${{ always() }}
        id: summary
        env:
          kernel_url: ${{ steps.publish-kernel.outputs.kernel_download_url }}
        continue-on-error: true
        run: |
          if [ "$kernel_url" != "" ]; then
            kernel_dir_url="${kernel_url%/*}"
            kernel_dir_name="${kernel_dir_url##*/}"
            result="Kernel build succeeded: [${kernel_dir_name}](${kernel_url})"
          else
            result="Kernel build failed."
          fi

          cat > summary << EEE
          ## Kernel Build Result
          
          $result
          EEE
          cat summary > $GITHUB_STEP_SUMMARY
          
          echo "summary_content<<EOF" >> $GITHUB_OUTPUT
          cat summary >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

