name: kunit-test

on:
  workflow_call:
    inputs:
      WORKFLOW_REPO:
        required: true
        type: string
        description: 工作流脚本仓库

      WORKFLOW_REF:
        required: true
        type: string
        description: 工作流脚本分支
        
      kernel_src_repo:
        type: string
        required: true
        description: '内核源码仓库'
      fetch_ref:
        type: string
        required: true
        description: '内核分支或sha值'
      issue_id:
        type: string
        required: false

jobs:
  kunit-test:
    runs-on: 'ubuntu-latest'

    env:
      REMOVE_LABEL: "kunit-test_waiting,kunit-test_checking,kunit-test_done"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ISSUE_ID: ${{ inputs.issue_id }}
      REPO: ${{ inputs.kernel_src_repo }}

    steps:
      - name: install pkg
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-riscv64-linux-gnu gcc-riscv64-unknown-elf make gcc g++ flex device-tree-compiler pahole dwarves libfuse-dev kmod  bzip2 xz-utils curl cpio bc libssl-dev libncurses-dev bison flex libelf-dev qemu-system-riscv64
      
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.WORKFLOW_REPO }}
          ref: ${{ inputs.WORKFLOW_REF }}
      
      - name: checkout kernel-src
        env:
          GIT_FETCH_DEPTH: 1
        run: |
            rm -rf kernel-src || true
            mkdir kernel-src
            (cd kernel-src && bash ../src/git-fetch-in-dir.sh "${{ inputs.fetch_ref }}")
      
      # - name: before
      #   env:
      #     ADD_LABEL: kunit-test_checking
      #     COMMENT_CONTENT: "start kunit test"
      #   run: bash gh_actions/run.sh || true

      - name: run kunit test
        run: |
          (
          cd kernel-src
          ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- bash ../kunit-test/kunit-test.sh &> $GITHUB_STEP_SUMMARY
          )

      # - name: after
      #   env:
      #     ADD_LABEL: kunit-test_done
      #   run: |
      #     COMMENT_CONTENT="kunit test done. log: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" bash gh_actions/run.sh || true

          