name: kunit-test

on:
  workflow_call:
    outputs:
      summary_content:
        value: ${{ jobs.kunit-test.outputs.summary_content }}
    inputs:
      kernel_src_repo:
        type: string
        required: true
        description: '内核源码仓库'

      fetch_ref:
        type: string
        required: true
        description: '内核分支或sha值'

jobs:
  kunit-test:
    outputs:
      summary_content: ${{ steps.run-kunit-test.outputs.sumary_content }}
    runs-on: 'ubuntu-latest'


    steps:
      - name: install pkg
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-riscv64-linux-gnu gcc-riscv64-unknown-elf make gcc g++ flex device-tree-compiler pahole dwarves libfuse-dev kmod  bzip2 xz-utils curl cpio bc libssl-dev libncurses-dev bison flex libelf-dev qemu-system-riscv64
      
      - name: checkout kernel-src
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.kernel_src_repo }}
          ref: ${{ inputs.fetch_ref }}
          fetch-depth: 1
      
      - name: run kunit test
        id: run-kunit-test
        continue-on-error: true
        run: |
          make distclean
          git checkout .
          ARCH=riscv CROSS_COMPILE=riscv64-linux-gnu- ./tools/testing/kunit/kunit.py run --arch=riscv > kunit.log 2>&1 || true
          result="$(grep 'Testing complete' kunit.log || echo "kunit test failed")"

          cat >> summary << EEE
          ## Kunit Test Result
          
          $result
          EEE

          echo "sumary_content<<EOF" >> $GITHUB_OUTPUT
          cat summary >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          cat > $GITHUB_STEP_SUMMARY <<- EEE
          $(cat summary)

          ### Kunit Test Log
          
          $(echo '```bash')
          $(cat kunit.log)
          $(echo '```')
          EEE
          
      # - name: after
      #   env:
      #     ADD_LABEL: kunit-test_done
      #   run: |
      #     COMMENT_CONTENT="kunit test done. log: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" bash gh_actions/run.sh || true

          